休息的时候看:
- htmlUrl: https://www.reddit.com/r/China_irl/
  name: 5ead30
  text: Reddit | China
  url: https://www.reddit.com/r/China_irl/.rss?
- htmlUrl: https://nitter.cz/whyyoutouzhele
  name: 32dc55
  text: 李老师不是你老师
  url: https://nitter.cz/whyyoutouzhele/rss
- htmlUrl: https://www.youtube.com/channel/UCghLs6s95LrBWOdlZUCH4qw
  name: 4544cf
  text: stone记
  url: https://www.youtube.com/feeds/videos.xml?channel_id=UCghLs6s95LrBWOdlZUCH4qw
- htmlUrl: https://www.youtube.com/channel/UCMUnInmOkrWN4gof9KlhNmQ
  name: 06044f
  text: KUAIZERO
  url: https://www.youtube.com/feeds/videos.xml?channel_id=UCMUnInmOkrWN4gof9KlhNmQ
- htmlUrl: https://www.reddit.com/r/ChatGPT
  name: 39fc13
  text: Reddit | ChatGPT
  url: https://www.reddit.com/r/ChatGPT/.rss
想买东西:
- htmlUrl: https://digi.ithome.com/
  name: 2c6c73
  text: IT 之家 | 数码
  url: https://rsshub.dcts.top/ithome/digi
  filters:
    - type: exclude
      field: title
      keywords: ["AMD", "惠普", "荣耀", "华为", "中兴", "Pixel"]
- htmlUrl: https://beta.sspai.com/tag/%E7%9C%8B%E5%AE%8C%E5%B0%B1%E6%83%B3%E4%B9%B0
  name: 563e67
  text: 少数派 | 好物推荐
  url: https://rsshub.dcts.top/sspai/tag/%E7%9C%8B%E5%AE%8C%E5%B0%B1%E6%83%B3%E4%B9%B0
- htmlUrl: http://www.smzdm.com
  name: c5738f
  text: 什么值得买 | 优惠精选
  url: http://feed.smzdm.com
  filters:
    - type: include
      field: title
      keywords: ["可乐", "雪碧", "芬达", "柠檬", "茶叶", "纸巾", "酒精", "湿纸巾", "餐巾纸"]
空闲的时候学会儿东西:
- htmlUrl: https://tophub.today/n/0MdKkV0dw1
  name: 0dfa04
  text: 竹白 | TOP20
  url: http://rsshub.dcts.top/tophub/0MdKkV0dw1
- htmlUrl: https://www.36kr.com/search/articless/%E7%BE%8E%E5%9B%A2
  name: 8c2e7b
  text: 36氪 | 美团
  url: https://rsshub.dcts.top/36kr/search/articles/%E7%BE%8E%E5%9B%A2
- htmlUrl: http://www.daemonology.net/hn-daily/
  name: 0593a5
  text: Hacker News | Daily
  url: http://www.daemonology.net/hn-daily/index.rss
  use_chatgpt: True
- htmlUrl: https://www.36kr.com/information/technology
  name: 392e02
  text: 36氪 | 科技
  url: https://rsshub.dcts.top/36kr/information/technology
- htmlUrl: https://www.36kr.com/information/ccs
  name: b6bc94
  text: 36氪 | 财经
  url: https://rsshub.dcts.top/36kr/information/ccs
- htmlUrl: https://sspai.com/matrix
  name: 5270ca
  text: 少数派 | Matrix
  url: http://rsshub.app/sspai/matrix
- htmlUrl: https://sspai.com/
  name: 7fc66f
  text: 少数派 | 推荐
  url: https://rsshub.app/sspai/index
- htmlUrl: https://m.okjike.com/topics/63579abb6724cc583b9bba9a
  name: 9d9e0d
  text: 即刻 | AIGC
  url: https://rsshub.app/jike/topic/63579abb6724cc583b9bba9a
- htmlUrl: https://www.reddit.com/r/ArtificialInteligence/
  name: 9e264f
  text: Reddit | AI
  url: https://www.reddit.com/r/ArtificialInteligence/.rss
- htmlUrl: https://www.infoq.cn/topic/AI
  name: d9bca1
  text: InfoQ | AI
  url: https://rsshub.dcts.top/infoq/topic/AI
- htmlUrl: http://www.ruanyifeng.com/blog/
  name: a120ad
  text: 阮一峰的网络日志
  url: http://feeds.feedburner.com/ruanyifeng
- htmlUrl: https://xlrocket.blog/
  name: b6780f
  text: 博客 | 效率火箭
  url: https://xlrocket.blog/feed
- htmlUrl: https://www.ezindie.com/weekly
  name: '221946'
  text: 博客 | 产品变现周刊
  url: https://www.ezindie.com/feed/rss.xml