basic:
  - use_chatgpt: False

rss:
  - url: https://rsshub.dcts.top/ithome/digi
    name: ithome
    filters:
      - type: include
        field: title
        keywords: ['键盘']
    use_chatgpt: True
    chatgpt:
        temperature: 0
  
  
