休息的时候看:
- htmlUrl: https://www.youtube.com/channel/UCghLs6s95LrBWOdlZUCH4qw
  name: 4544cf
  text: stone记
  url: https://www.youtube.com/feeds/videos.xml?channel_id=UCghLs6s95LrBWOdlZUCH4qw
- htmlUrl: https://www.youtube.com/channel/UCMUnInmOkrWN4gof9KlhNmQ
  name: 06044f
  text: KUAIZERO
  url: https://www.youtube.com/feeds/videos.xml?channel_id=UCMUnInmOkrWN4gof9KlhNmQ
- htmlUrl: https://nitter.cz/zu1k_
  name: c94380
  text: zu1k
  url: https://nitter.cz/zu1k_/rss
- htmlUrl: https://nitter.cz/zuozizhen
  name: c0f3c6
  text: 左子祯
  url: https://nitter.cz/zuozizhen/rss
- htmlUrl: https://nitter.cz/chinesehuazhou
  name: 75d5f1
  text: 豌豆花下猫
  url: https://nitter.cz/chinesehuazhou/rss
- htmlUrl: https://nitter.cz/iamairyland
  name: 573f62
  text: Airyland | code.bit
  url: https://nitter.cz/iamairyland/rss
- htmlUrl: https://nitter.cz/ruanyf
  name: 9f46f1
  text: ruanyf
  url: https://nitter.cz/ruanyf/rss
- htmlUrl: https://nitter.cz/dynamicwangs
  name: 2be3e8
  text: DynamicWang
  url: https://nitter.cz/dynamicwangs/rss
- htmlUrl: https://nitter.cz/jike_collection
  name: cec9a5
  text: 即刻精选
  url: https://nitter.cz/jike_collection/rss
- htmlUrl: https://nitter.cz/FinanceYF5
  name: 26db64
  text: Will
  url: https://nitter.cz/FinanceYF5/rss
- htmlUrl: https://nitter.cz/GPTDAOCN
  name: 83e842
  text: GPTDAOCN-e/acc
  url: https://nitter.cz/GPTDAOCN/rss
- htmlUrl: https://nitter.cz/quinn_leng
  name: '748684'
  text: Quinn Leng
  url: https://nitter.cz/quinn_leng/rss
- htmlUrl: https://nitter.cz/xiaohuggg
  name: 29dc6c
  text: 小互
  url: https://nitter.cz/xiaohuggg/rss
- htmlUrl: https://nitter.cz/iguangzhengli
  name: 05db7e
  text: Guangzheng Li
  url: https://nitter.cz/iguangzhengli/rss
- htmlUrl: https://nitter.cz/Gorden_Sun
  name: 0be6f2
  text: Gorden Sun
  url: https://nitter.cz/Gorden_Sun/rss
- htmlUrl: https://nitter.cz/sama
  name: 319cf2
  text: Sam Altman
  url: https://nitter.cz/sama/rss
- htmlUrl: https://nitter.cz/dotey
  name: b88f17
  text: 宝玉
  url: https://nitter.cz/dotey/rss
- htmlUrl: https://nitter.cz/op7418
  name: fc1be9
  text: 歸藏
  url: https://nitter.cz/op7418/rss
- htmlUrl: https://nitter.cz/OpenAI
  name: ea539b
  text: OpenAI
  url: https://nitter.cz/OpenAI/rss
想买东西:
- htmlUrl: https://digi.ithome.com/
  name: 2c6c73
  text: IT 之家 | 数码
  url: https://rsshub.dcts.top/ithome/digi
- htmlUrl: https://beta.sspai.com/tag/%E7%9C%8B%E5%AE%8C%E5%B0%B1%E6%83%B3%E4%B9%B0
  name: 563e67
  text: 少数派 | 好物推荐
  url: https://rsshub.dcts.top/sspai/tag/%E7%9C%8B%E5%AE%8C%E5%B0%B1%E6%83%B3%E4%B9%B0
- htmlUrl: http://www.smzdm.com
  name: c5738f
  text: 什么值得买 | 优惠精选
  url: http://feed.smzdm.com
  filters:
    - type: include
      field: title
      keywords: ["可乐", "雪碧", "芬达", "柠檬", "茶叶", "纸巾", "酒精", "湿纸巾", "餐巾纸", "垃圾袋", "玩具", "水果", "拼多多", "鼠标"]
空闲的时候学会儿东西:
- htmlUrl: https://www.36kr.com/search/articless/%E7%BE%8E%E5%9B%A2
  name: 8c2e7b
  text: 36氪 | 美团
  url: https://rsshub.dcts.top/36kr/search/articles/%E7%BE%8E%E5%9B%A2
- htmlUrl: https://www.36kr.com/information/technology
  name: 392e02
  text: 36氪 | 科技
  url: https://rsshub.dcts.top/36kr/information/technology
  use_chatgpt: True
- htmlUrl: https://www.36kr.com/information/ccs
  name: b6bc94
  text: 36氪 | 财经
  url: https://rsshub.dcts.top/36kr/information/ccs
  use_chatgpt: True
- htmlUrl: https://sspai.com/matrix
  name: 5270ca
  text: 少数派 | Matrix
  url: http://rsshub.app/sspai/matrix
  use_chatgpt: True
- htmlUrl: https://sspai.com/
  name: 7fc66f
  text: 少数派 | 推荐
  url: https://rsshub.app/sspai/index
  use_chatgpt: True
- htmlUrl: https://m.okjike.com/topics/63579abb6724cc583b9bba9a
  name: 9d9e0d
  text: 即刻 | AIGC
  url: https://rsshub.app/jike/topic/63579abb6724cc583b9bba9a
- htmlUrl: https://www.infoq.cn/topic/AI
  name: d9bca1
  text: InfoQ | AI
  url: https://rsshub.dcts.top/infoq/topic/AI
  use_chatgpt: True
- htmlUrl: http://www.ruanyifeng.com/blog/
  name: a120ad
  text: 阮一峰的网络日志
  url: http://feeds.feedburner.com/ruanyifeng
