name: Sync Docs and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout main repo
        uses: actions/checkout@v4.1.0
          
      - name: Checkout gh repo
        uses: actions/checkout@v4.1.0
        with:
          repository: TD21forever/TD21forever.github.io
          ref: source
          path: gh

      - name: Copy docs from current repository to gh-source repository
        run: |
          cp -R docs/* gh/source/rssdocs/

      - name: Configure Git
        run: |
          git config --global user.name "td21forever"
          git config --global user.email "435212619@qq.com"
          cd gh
          npm install

      - name: Install dependencies and build
        run: |
          cd gh
          npm install
          export GIT_TOKEN=${{ secrets.KEY }}
          npx hexo g -d
          
      - name: Commit and push changes to B repository
        run: |
          cd TD21forever.github.io
          git add .
          git commit -m "Sync docs from main repository"
          git push origin source
